version: '2'
services:
  lobby:
    build:
      context: .
      dockerfile: Dockerfile
      target: lobby
      args:
        VITE_SERVER_URL: "http://localhost:8000"
    ports:
      - "3000:80"
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      args:
        ORIGIN_URL: "localhost:3000"
    ports:
      - "8000:8000"
  tictactoe:
    build:
      context: .
      dockerfile: Dockerfile
      target: tictactoe
    ports:
      - "3001:80"
