name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - run: yarn install --pure-lockfile
      - run: yarn lint --cache --quiet
      - run: yarn prettier:check
      - run: yarn tsc --noEmit
      - run: yarn test
